### ISSUE TITLE
Git exe required for execution

### ISSUE THREAD

**Issue by rand-monkey** [NetherlandsForensicInstitute/qnxmount#2]
Placeholder requested by Francis.

On Ubuntu 22 VM, used: 
pip3 install qnxmount
to install.

Launching with:
python3 -m qnxmount efs image mnt
resulted in:
FileNotFoundError: [Errno 2] No such file or directory: 'git'

Installing git resolved the error.

**Comment by FrancisHoogendijk** [comment]
Sorry for the long delay, this should be fixed with the changes I just made. 
I also pushed a new version: 0.1.5 to pypi
